services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale_control
    restart: always
    command: sleep infinity
    ports:
      - "8080:8080"
    volumes:
      - ./headscale_config:/etc/headscale
      - ./headscale_data:/var/lib/headscale
