HTTP/1.0 405 Method Not Allowed
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>405 Method Not Allowed</h1><p>The method specified in the Request-Line is not allowed for the resource identified by the Request-URI.</p></body></html>
